In [1]:
import numpy as np

### Generate a 5×4 array of random integers between 20 and 100 (inclusive).
Then for each column, find:

- Minimum value
- Maximum value
- Mean (average)
- The row index where maximum occurs in that column

Print everything nicely (maybe using a loop only for printing, not for calculation).

In [ ]:
# randint for integer number 
a=np.random.randint(20,101,size=(5,4))
a

array([[ 40,  85,  48,  58],
       [ 48,  91,  72,  87],
       [ 52, 100,  21,  44],
       [ 84,  82,  41,  40],
       [ 35,  35,  22,  41]], dtype=int32)

In [40]:
# min_value=np.min(a,axis=0)
# max_value=np.max(a,axis=0)
# avg=np.mean(a,axis=0)
np.argmax(a,axis=0)

array([3, 2, 1, 1])

In [ ]:
# generates random number bw 0-1
np.random.random(size=(5,4))

array([[0.40746793, 0.32919677, 0.60236774, 0.29184647],
       [0.59490122, 0.86133114, 0.45459719, 0.33762603],
       [0.18444435, 0.73060058, 0.88777291, 0.84729468],
       [0.88443355, 0.54017711, 0.68656076, 0.92798575],
       [0.82151859, 0.93831145, 0.916131  , 0.91127736]])

In [33]:
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
np.random.rand()

0.7324890342629173