In [1]:
import numpy as np

### Create this pattern without loops (use padding + tiling tricks):
[[0 0 0 1 1 1 0 0 0]

 [0 0 0 1 1 1 0 0 0]

 [1 1 1 1 1 1 1 1 1]

 [1 1 1 1 1 1 1 1 1]

 [0 0 0 1 1 1 0 0 0]
 
 [0 0 0 1 1 1 0 0 0]]

Shape should be (6,9). Center 3×3 should be 1s in a cross shape, rest 0s.

(Hint: start with small array and use np.pad, np.tile, or np.repeat)

In [24]:
a=np.array([1,1,1])

x=np.pad(a,pad_width=(3,3),mode='constant',constant_values=(0))
y=np.pad(a,pad_width=(3,3),mode='constant',constant_values=(1))

base=np.vstack([x,y,x])
final=np.repeat(base,2,axis=0)
# final
x

array([0, 0, 0, 1, 1, 1, 0, 0, 0])

In [ ]:
a=np.array([1,0,1]) # 1d array

b=np.array([[1,0,1],[1,0,2]]) # 2d array

c=np.repeat(a,2,axis=0)

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 2],
       [1, 0, 2]])