In [1]:
import numpy as np

### Given Array
A = np.arange(1, 7).reshape(2,3)     # 1 2 3 / 4 5 6

B = np.arange(7, 13).reshape(2,3)    # 7 8 9 / 10 11 12

C = np.arange(13, 19).reshape(2,3)   #13 14 15 / 16 17 18

- Stack them horizontally → shape should be (2,9)
- Stack them vertically → shape should be (6,3)
- Now take the horizontally stacked array and split it back into 3 equal parts (column-wise)

In [12]:
a = np.arange(1, 7).reshape(2,3)     # 1 2 3 / 4 5 6
b = np.arange(7, 13).reshape(2,3)    # 7 8 9 / 10 11 12
c = np.arange(13, 19).reshape(2,3)   #13 14 15 / 16 17 18


# np.stack((A,B),axis=1)

h_stack=np.hstack((a,b,c))
v_stack=np.vstack((a,b,c))
f=np.hsplit(h_stack,3)
f

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [ ]:
h=np.concatenate((a,b,c),axis=1)
v=np.concatenate((a,b,c),axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])